### ISSUE TITLE
What theme will the website use?

### ISSUE THREAD

**Issue by timtrice** [rfordatascience/website#10]

**Comment by martinjhnhadley** [comment]
There are two options in my mind:

| [Academic Theme](https://themes.gohugo.io/academic/) | [Universal Theme](https://github.com/devcows/hugo-universal-theme) | 
| -- | -- |
| Example: [Jesse's site](https://www.jessemaegan.com/#talks) | Example: [Quanteda Site](https://quanteda.io/)

The major differences (as I see them) are detailed in the table below:

| Feature | PRO | CON | Theme with feature |
| -- | -- | -- | -- |
| Single Page | Simple to maintain and keeps site small | Difficult to expand website into new areas, integrating new themed day details | Academic Theme |
| Multi-Page | Allows site to expand easily, new themed days can be added as new pages | Harder to maintain | Universal Theme |
| Customisability with Boostrap | Allows responsively pages to be designed | Requires some CSS/HTML knowledge | Universal Theme |
| Simplicity of template | Contributors need only learn RMarkdown, no need to learn HTML/CSS | Reduces customisability | Academic Theme

We could agree a reaction polling system to choose between the two - if there are no other contenders  😀

**Comment by timtrice** [comment]
Universal Theme incorporated in PR #22
