### ISSUE TITLE
Set up site on Netlify

### ISSUE THREAD

**Issue by timtrice** [rfordatascience/website#11]

**Comment by timtrice** [comment]
@kierisi this may be a task only you can do. Netlify does not show rfordatasicence as a group I can add. 

To note, we should use the following settings under deployment:

**Deploy settings**
* Branch to deploy:  master
* Build command: hugo
* Publish directory: public

**Build environment variables**
* HUGO_VERSION: 0.38.2 (latest release as of today. 0.38 was released around the first so perhaps we can use that one instead?)

[Blogdown > 3.1 Netlify](https://bookdown.org/yihui/blogdown/netlify.html)

**Comment by kierisi** [comment]
this should be resolved - I needed to log in and give Netlify access to the organization. while I was in there I set up the requested deploy settings and build environment variables, but you should also be able to adjust these from your end as well.

let me know if that's not the case, and I'll dig around and see if I can figure out how to set that up.

**Comment by timtrice** [comment]
You may need to set up the domain as well. I can add it as a website but I have no idea where your site was built. So, when you get a chance, you can add the domain and provide the DNS details to your name server and,I believe, the site should go live.

Something also to consider though not required. I enabled SSL/TLS on mine. Not going to lie - I only did it for the security lock in the browser address bar. :)

But, to the best of my knowledge the Netfliy-side of this you will have to manage alone (on the free plan). Which should be fine as little maintenance is involved after initial setup. 

Again, I could be wrong about any of this. I'm only familiar with using it for personal non-group usage.

**Comment by kierisi** [comment]
I've set up the domain - thank you for reminding me! you should be live now (I'm showing that on my end).

I'll set up the SSL/TLS tomorrow. the DNS zone has to be "live" for at least an hour, and I'm probably not going to be up that long 😴

**Comment by timtrice** [comment]
Looks good on my end, @kierisi. Thanks!
