### ISSUE TITLE
Update config.toml params

### ISSUE THREAD

**Issue by timtrice** [rfordatascience/website#15]
Modify config.toml parameters:

* title -  Correct title of website
* googleAnalytics - get with @kierisi to see if there is a Analytics code to use
* disqusShortname - Again, check with @kierisi if this is avaialble
* description - No description has really been given but can be updated. 
* Modify params.logo alt to "R For Data Science Community" (verify this is correct).

**Comment by stefanreifenberg** [comment]
I am currently working on this issue
