### ISSUE TITLE
Add Contributing.MD

### ISSUE THREAD

**Issue by timtrice** [rfordatascience/website#17]
See  https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by mraza007** [comment]
Hi I can help you add the Contributing.Md to repo

**Comment by mraza007** [comment]
You mean fork this repo and add contributing.md file then open a pull request.
Do you want me to follow the GitHub template for the contributing.md

**Comment by timtrice** [comment]
If you haven't already forked the repo then you will not need to create the directory as it has already been created in master and develop branch. So, just put the template into the .github directory. 

Using GH's template is fine.
