### ISSUE TITLE
Update "Who?" on home page

### ISSUE THREAD

**Issue by timtrice** [rfordatascience/website#29]
Currently, the "Who?" block (testimonials in the universal theme) are placeholders. These should be updated to actual testimonials.

**Comment by timtrice** [comment]
@kierisi, do you have thoughts on this? If you agree, would you like to put a request for testimonials on the general Slack channel or twitter?

**Comment by timtrice** [comment]
How-to on adding testimonials has been added to the wiki:

https://github.com/rfordatascience/website/wiki/Adding-Testimonials

**Comment by kierisi** [comment]
@timtrice this is fantastic! you're an admin in Slack now (you may have to reload the app/browser), so feel free to ask in general using @channel!

**Comment by mGrossSRT** [comment]
Hey guys, do you mind if I grab this issue?

**Comment by kierisi** [comment]
fine by me - I believe @timtrice might have some info to help with this!

**Comment by timtrice** [comment]
Have at it! The first four cards can be removed and Andrea's card can be renumbered to 1. We need more testimonials so feel free to provide one.

**Comment by mGrossSRT** [comment]
@timtrice I didn't check the language used before commenting. I never used R to program websites/apps. Can you indicate me the best way to dev and what I need to test the web?

**Comment by timtrice** [comment]
For this particular issue, you do not need R.  R is really more of a data/stats tool; it is not a web-based language. 

That being said, there is a package that allows users to generate a personal blog with Hugo which is what this repo uses. So, if you have Hugo installed on your system you should be able to tackle this issue. 

Our articles will mostly be in Rmd format which requires R to "translate". Currently, we have HTML docs alongside so if you serve the site locally through Hugo you may be able to get away with it. But, I can't guarantee that at this point.

**Comment by timtrice** [comment]
@mGrossSRT, do you still want this issue to be assigned to you?

**Comment by jonthegeek** [comment]
The website has been deemphasized (it's just a portal into Slack and soon the other projects), so this is no longer needed.
