### ISSUE TITLE
Add email page or contact form

### ISSUE THREAD

**Issue by timtrice** [rfordatascience/website#5]
Email address: rfordatasci@gmail.com

Please reach out to Jesse in the Slack community when you need information from the account. 

Netlify offers form support; not a requirement but an option.

**Comment by timtrice** [comment]
Needs resolution of #9

**Comment by timtrice** [comment]
Unresolved.

**Comment by jonthegeek** [comment]
We have a mailto on the top bar, I think that suffices for now.
